baseURL = "https://heuristic-johnson-d1e621.netlify.com/"
languageCode = "ja-jp"
title = "Amusement Creators New Website Prototype"
theme = "ananke"
background_color_class = "bg-white"
featured_image = "/images/hero.png"
hasCJKLanguage = true

[params]
  description = "筑波大学 Amusement Creators"
  images = ["/images/logo.png"]
  twitter = "https://twitter.com/ac_is_not_am"


[menu]
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Works"
    identifier = "works"
    url = "/post/works/"

  [[menu.main]]
    name = "Members"
    identifier = "members"
    url = "/members/"