baseURL = "https://heuristic-johnson-d1e621.netlify.com/"
languageCode = "ja-jp"
title = "Amusement Creators New Website Prototype"
theme = "ananke"
background_color_class = "bg-white"

[params]
  description = "筑波大学 Amusement Creators"
  images = ["/images/logo.png"]

[menu]
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"